version: '3'
services:
  course-scheduler:
    image: jojopnz/sds-course-scheduler
    container_name: regsds-course-scheduler
    env_file:
      - .env
    environment:
      - PORT=5001
    ports:
      - '5001:5001'
  grade-calculator:
    image: abcdeclair/sds-grade-calculator
    container_name: regsds-grade-calculator
    env_file:
      - .env
    environment:
      - PORT=5002
    ports:
      - '5002:5002'
  grade-assessment:
    image: jojopnz/sds-grade-assessment
    container_name: regsds-grade-assessment
    env_file:
      - .env
    environment:
      - GRADE_ASSESSMENT_PORT=5003
    ports:
      - '5003:5003'
  pdf-generator:
    image: nitiwatowen/regsds-pdf-generator
    container_name: regsds-pdf-generator
    env_file:
      - .env
    environment:
      - PORT=5004
    ports: 
     - '5004:5004'
